### ISSUE TITLE
ARIA support

### ISSUE THREAD

**Issue by vasco3** [thoughtbot/refills#110]
The refills have no Aria support for accessibility. 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**Comment by Magnus-G** [comment]
@vasco3 we have added some `role` tags where appropriate. Since many of the components can be used in different ways I am hesitant to using tags for some of them. Please take a look and see if you miss anything.

**Comment by teoljungberg** [comment]
Closing this issue for now, please open new issues if there are anything else we can do to increase the ARIA support for the documentation.

Thanks!
