### ISSUE TITLE
Undefined variable "$large-screen"

### ISSUE THREAD

**Issue by wighawag** [thoughtbot/refills#113]
Hi,

Just trying out the bourbon/neat/bitters/refills combo and after setting a basic project injecting only the first navigation pattern, I get the following error : Undefined variable "$large-screen"

Is the docs not up to date or am I doing something wrong?

**Comment by slothyrulez** [comment]
+1 for the semicolon...

**Comment by acandael** [comment]
I ran into the same problem. Solved the issue by adding a semi-colon after:

    @import "../neat/neat-helpers";

in my base/_grid_settings.scss file
