### ISSUE TITLE
Update README (and new gem release?)

### ISSUE THREAD

**Issue by cllns** [thoughtbot/refills#141]
Thanks for Refills, it's wonderful!

I found a couple issues in the README, both having to do with an outdated gem release (and using the generator)

1. The content from this commit (https://github.com/thoughtbot/refills/commit/d97b0e1a7c04eb9ada4e0451e5c55f6021636ca9) is still in the README but it's outdated. Now the refills site (http://refills.bourbon.io/) shows 3 columns for HTML/CSS/JS separately.

If the user follows the directions in the README, they'll get release 0.0.2 and, if they use the generator, they'll get a view that has both the HTML and the JS together, instead of separately like HEAD does now (and says below in the README). Which leads me to my next point...

2. The last gem release was 0.0.2 in May. Perhaps it's time for 0.0.3?

I expected to require the Gem and get the versions of the refills that are on the site (http://refills.bourbon.io/) when using the generator but that's not the case.

Naturally this is unavoidable unless there's a new gem release for each commit, so maybe there should be something in the README to that effect, saying you should do the following if you want the most recent copy of the refills?
 ```gem "refills", git: "git://github.com/thoughtbot/refills.git"```

Thoughts?

**Comment by teoljungberg** [comment]
@cllns - we're planning out the releases for refills right now, and a new version will be released very soon. It should be within the next few days

**Comment by cllns** [comment]
@teoljungberg great! :+1:

**Comment by teoljungberg** [comment]
Since I just released `0.1.0` of refills, I'm closing this

/cc @cllns

**Comment by maurogeorge** [comment]
:+1: thanks for the release

**Comment by cllns** [comment]
Woo hoo! :+1:
