### ISSUE TITLE
hero on ie 9 & navigation dropdown menu on phones

### ISSUE THREAD

**Issue by michaelryu** [thoughtbot/refills#163]
Hero is not loading on ie 9 and dropdown from nav menu will only work once before needing a refresh of the phone browser. I've tried this on android chrome as well as firefox.

**Comment by Magnus-G** [comment]
@michaelryu I have now added a `background-color` to the hero. 
I don't have any issues with the nav though so if you're still experiencing that please add another issue!
Maybe I just wasn't able to recreate the issue?

Thanks
