### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by iryanclarke** [thoughtbot/refills#164]
I absolutely love Refills and the whole Bourbon family, and I want to contribute a new component, but I am a bit confused how develop a new one using this stack. 

I'm completely comfortable doing the SASS/HTML scaling and development, I'm just confused how to set up/view my development changes!

Any help is appreciated, thanks! :)

**Comment by jhenderson22** [comment]
@iryanclarke any luck with the video hero unit, I was pondering on doing one as well...

**Comment by iryanclarke** [comment]
I'm nearly done it, just polishing it up! :P Still need to commit it into my forked repo :V

**Comment by jhenderson22** [comment]
@iryanclarke awesome, please let me know when it's available, I would love to have a look...

**Comment by iryanclarke** [comment]
I'll let you know, school is bearing down hard so I'll do it when I can!
