### ISSUE TITLE
nav menu opens en immediatly closes when clicked

### ISSUE THREAD

**Issue by acandael** [thoughtbot/refills#176]
Hi,

I just noticed an issue with the responsive nav menu. On mobile screens, when clicked, it drops down, but then immediately pulls up again. Or it drops down and pulls up a couple of times before it definitly stays pulled up.

you can see this in action here:

http://178.62.173.211/

I had no issues before with the responsive nav menu. The problem started when implementing the jquery-turbolinks gem. I had to implement this gem, because I had issues with some jquery plugins, caused by Rails turbolinks.

I just copied and pasted the script from Bourbon Refills:

    <script>
    $(document).ready(function() {
      var menu = $('#navigation-menu');
      var menuToggle = $('#js-mobile-menu');
      var signUp = $('.sign-up');

      $(menuToggle).on('click', function(e) {
        e.preventDefault();
        menu.slideToggle(function(){
          if(menu.is(':hidden')) {
            menu.removeAttr('style');
          }
        });
      });

 Is there a quick way to fix this?
 // underline under the active nav item
  $(".nav .nav-link").click(function() {
    $(".nav .nav-link").each(function() {
      $(this).removeClass("active-nav-item");
    });
    $(this).addClass("active-nav-item");
    $(".nav .more").removeClass("active-nav-item");
  });
});
</script>

**Comment by Magnus-G** [comment]
@acandael thank you for catching this!

I've changed the code to this:

```
$(document).ready(function() {
  var menuToggle = $('#js-mobile-menu').unbind();
  $('#js-navigation-menu').removeClass("show");

  menuToggle.on('click', function(e) {
    e.preventDefault();
    $('#js-navigation-menu').slideToggle(function(){
      if($('#js-navigation-menu').is(':hidden')) {
        $('#js-navigation-menu').removeAttr('style');
      }
    });
  });
});
```

Does that do the trick?
