### ISSUE TITLE
Maps partial using id instead of class

### ISSUE THREAD

**Issue by stjernegard** [thoughtbot/refills#181]
In `_maps.html.erb` line 52 `bodyContent` is referred to as `<div id="bodyContent">`, but in `_maps.scss` line 20 and 26, it is referred to as `.bodyContent`.

**Comment by derekblank** [comment]
Issue updated here: https://github.com/thoughtbot/refills/pull/184/files#diff-62ab25dc87a3823b47eb1da3e597308fR38

**Comment by Magnus-G** [comment]
@stjernegard this should be fixed now.
