### ISSUE TITLE
Missing parallax component on the 'generate refills:list'

### ISSUE THREAD

**Issue by matheusagcosta** [thoughtbot/refills#185]
I'm using refills v0.0.2

![screen shot 2015-01-07 at 11 05 18](https://cloud.githubusercontent.com/assets/3741582/5645959/73c67eea-965d-11e4-92da-afa136c949a3.png)

**Comment by cllns** [comment]
In your Gemfile, if you change this line:
```
gem 'refills'
```

to:
```
gem 'refills', github: 'thoughtbot/refills'
```

(and run `bundle` again)

Then you'll get the current version of refills from Github, rather than the out-of-date one from Rubygems.

I have an issue open that would fix this: https://github.com/thoughtbot/refills/issues/141

**Comment by matheusagcosta** [comment]
@cllns thanks for the help bro.
