### ISSUE TITLE
Remove “Browser” pattern

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/refills#211]
I’m suggesting that we remove the “[Browser](http://refills.bourbon.io/#browser)” pattern.

It’s not best-practice to create visual graphic via empty `div`’s and CSS. SVG would be a much better route.

Also, Will’s new “[Foundry](http://thoughtbot.github.io/foundry)” has an SVG browser.

**Comment by Magnus-G** [comment]
@tysongach is there a good way to use SVG and incorporate an image? For instance if I want to put a screenshot in one of the iPad SVG's on Will's site.

**Comment by tysongach** [comment]
You can embed images inside SVG’s: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_Image_Tag

@whmii might have a little more context?

**Comment by Magnus-G** [comment]
Maybe it'd be good to update this pattern to an SVG version? It'd be nice to have a generic SVG graphic with an image in it. I could see a few good use cases for that.

Or do you want to just get rid of it?

**Comment by whmii** [comment]
I'd be more for just getting rid of this one. It's specific to such a degree that I feel it's difficult to call it a 'pattern'

**Comment by tysongach** [comment]
I agree with removing it from Refills. Let’s focus on the other patterns and components first. Maybe down the road we'll see how this can better be incorporated.

**Comment by Magnus-G** [comment]
Removing it!

**Comment by tysongach** [comment]
@Magnus-G I don’t think the PR above was every submitted.

**Comment by Magnus-G** [comment]
Sorry: https://github.com/thoughtbot/refills/pull/224

**Comment by teoljungberg** [comment]
Closed by #224
