### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by vko-online** [thoughtbot/refills#213]
in `src/app/index.scss` i write
```scss
   @import "../bower_components/refills/source/stylesheets/all";
```
 But it throws 
```js
   error index.scss (Line 6: File to import not found or unreadable: ../bower_components/refills/source/stylesheets/all.
```
Do i need to build it? Importing main file i enough thought

**Comment by tysongach** [comment]
Installation instructions can be found [here](https://github.com/thoughtbot/refills#installation).

We don’t officially support or recommend using Bower (someone else probably added it to Bower’s database); it’s best to copy-paste into your project or use the Rails generator. Bower is more for things that you never plan on editing; but we expect you to change and edit Refills to fit your project.

**Comment by vko-online** [comment]
Great, thanks
For guys who struggle with this a bit, install it from gem, it's easier
