### ISSUE TITLE
Is there a specific version of JQuery required?

### ISSUE THREAD

**Issue by ravenwilde** [thoughtbot/refills#218]
Additionally, if there is a specific version of JQuery can you please add it to the README? Thanks.

**Comment by Magnus-G** [comment]
@ravenwilde did you run into trouble with a specific version of jQuery? Our intent is that Refills should always work with the latest version, or at least the version used on the site!

**Comment by ravenwilde** [comment]
No problems, I'm just currently working on backwards compatibility for IE 8 and contemplating my options. Any advice?

**Comment by cllns** [comment]
@ravenwilde You should use 1.x of jQuery, since 2.x intentionally doesn't support IE8. http://jquery.com/browser-support/

**Comment by ravenwilde** [comment]
yeah that's about what I'd determined... thanks for the confirmation though :)
