### ISSUE TITLE
Accordion Tabs

### ISSUE THREAD

**Issue by shakna-israel** [thoughtbot/refills#220]
Okay, this is bugging the hell out of me, now.

I set up as simple a demo as I could, using Bourbon, Neat, and the Accordion Tabs css.

I compiled all three using Sass 3.4.9.

I added jQuery 1.11.2, and the script for the tabs.

This is brain-dead simple, and simply does not work at all.

[The brain-dead](https://shakna-israel.github.io/refills-test/) demo.

What on earth is missing, here?

**Comment by Magnus-G** [comment]
@shakna-israel are you sure you're loading jQuery the right way? In my `head` I have

`<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>`

...and it works. If I remove that one, or change it, I get the same result as you. I see that the `js` file is loaded but it doesn't seem to work for you.
If you still have trouble you can post your code and/or a screenshot of your document tree (to show how your files are set up).

**Comment by shakna-israel** [comment]
If, in this tiny demo, I replace the local jQuery request with the API one, it doesn't seem to make a difference.

The whole thing is up at https://github.com/shakna-israel/refills-test/tree/gh-pages , because I've been trying to find out exactly where this whole thing is going wrong.

**Comment by Magnus-G** [comment]
@shakna-israel taking a look...

**Comment by Magnus-G** [comment]
@shakna-israel I think I found it. You wrote `test` instead of `text` in the script call. Try changing that and use an html that looks something like this:

<!doctype html>
<html>
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="main.css" />     
</head>
  
<body>
   `accordion-tabs code here`
   <script type="text/javascript" src="tabs.js"></script>
</body>
</html>

**Comment by shakna-israel** [comment]
Holy crap. Well, that's embarrassing. Thankyou, and sorry for being such a pain. The mispelling was the cause.
