### ISSUE TITLE
Missing semicolon in accordion_tabs_minimal

### ISSUE THREAD

**Issue by h0wn0w** [thoughtbot/refills#228]
From line 9, which reads:

`var accordionTabs = $(this).closest('.accordion-tabs-minimal')`

should be: 

`var accordionTabs = $(this).closest('.accordion-tabs-minimal');`

**Comment by Magnus-G** [comment]
@h0wn0w Thanks! Would you like to create a PR?

**Comment by h0wn0w** [comment]
Sure thing; I wasn't totally sure if it was an appropriate move for this correction. Will submit within the hour when I get back to my office.
