### ISSUE TITLE
Inifinite loop when building gem

### ISSUE THREAD

**Issue by croaky** [thoughtbot/refills#231]
I just attempted to bump the version number and then bundle but witnessed an infinite loop in Bundler's resolver.

**Comment by teoljungberg** [comment]
I just released `0.1.0` of refills, and from thoughtbot/suspenders#476 you mentioned that it was a problem with the `github` filter for bundler, which you shouldn't need to use anymore.

**Comment by croaky** [comment]
@teoljungberg Nice. I was able to bundle with a fresh clone of Refills.
