### ISSUE TITLE
Slide Menu Problem

### ISSUE THREAD

**Issue by johngibbons** [thoughtbot/refills#238]
The "Sliding Menu" button click event only works for the first page it is loaded on.  Once you click one of the links to take you to a new page, clicking on the nav button no longer produces a result.

**Comment by Magnus-G** [comment]
@johngibbons thanks for the heads up! We'll look at this.

**Comment by Magnus-G** [comment]
@johngibbons It works fine here. Can you be more specific on how you do this? Or send some code?

![aaa](https://cloud.githubusercontent.com/assets/2095625/5977707/810af690-a89a-11e4-81ba-374cac14544b.gif)

**Comment by Magnus-G** [comment]
@johngibbons Closing this for now. Please re-open if the problem remains the same.
