### ISSUE TITLE
Footer 2 sticky height/bottom margin issue...

### ISSUE THREAD

**Issue by rikkipitt** [thoughtbot/refills#249]
Hey guys,

Is anyone else experiencing the following with the footer-2 in sticky mode? It causes a slight page scroll on pages that are less than 100% in height. It also appears that the footer is smaller when compared to the non-sticky version... any ideas? The dark grey is my desktop background for reference.

Cheers

![screen shot 2015-02-06 at 15 19 08](https://cloud.githubusercontent.com/assets/1147871/6081776/17ee1b72-ae14-11e4-948c-1f76017ce061.png)

**Comment by louisnovick** [comment]
I am not 100% certain if you're having the same problem I had but here is the piece of sass I edited to get it to stick to the bottom.  No issues yet but I could be mistaken.

`.footer-2, .wrapper-for-content-outside-of-footer:after {
   height: 17em;

   @include media($large-screen) {
     height: 4.5em;
	 bottom: 0;
	 position: absolute;
   }
 }`

**Comment by rikkipitt** [comment]
Hey @louisnovick, that's exactly the fix I did too. The default height is height: 4em; so the complete fix is to add bottom 0 and absolute position and update the height from 4 to 4.5em as in your snippet!

Rikki

**Comment by rikkipitt** [comment]
Position absolute didn't actually fix the issue on longer pages, please ignore my now closed pull request.

**Comment by rikkipitt** [comment]
It was actually the ```display: inline-block;``` on .footer-2
