### ISSUE TITLE
Refills Cards and Refills Flex Boxes don't work in Android Browser

### ISSUE THREAD

**Issue by fabriziotappero** [thoughtbot/refills#258]
Refills Cards and Refills Flex Boxes as shown in the example here
http://refills.bourbon.io/
don't work in the default Android Browser (maybe Android jelly bean, not sure). Specifically the problem has to do with their width and seem to span all the way as if the page was 6 or 7 times larger.

No problem in Android Chrome but because of the magnitude of the problem I think it is kind of important to fix it.

**Comment by Magnus-G** [comment]
@fabriziotappero I think this is due to the fact that the Android default browser doesn't support flexbox. However, all the new Android phones are shipped with Chrome and it seems like the default browser is being phased out. We have therefore decided not to support it. Sorry if this causes trouble. If it does, you can use Neat instead of flexbox for those components to have them laid out the way you like.

**Comment by fabriziotappero** [comment]
Hi, I totally understand. What do you exactly mean by using Neat?
There are unfortunately lots of Android tablets out there with this Browser. If the problem was minor I would not care but the actually problem is a massive width problem. I personally need to fix this. At the end of the day is just a flexible box.

Please advise how to use Neat for this.

thanks a lot

**Comment by Magnus-G** [comment]
@fabriziotappero I'd pull out all of the flexbox styles and just use `@include span-columns(4);` for each card. See more info at http://thoughtbot.github.io/neat-docs/latest/

**Comment by fabriziotappero** [comment]
How interesting all these mixing thing... I will have a look this we. Thanks a lot for your great support.

**Comment by fabriziotappero** [comment]
Hi,
I have being try to fix this with mild success. The problem is that Neat
span-columns needs omega resetting every time you redefine column span,
something that you do for responsive websites. This guy explains the
problem and the solution:

http://www.joshfry.me/blog/2013/05/13/omega-reset-for-bourbon-neat

I feel like I am missing a grid system... Is there any simpler use of omega?

Regards
Fabrizio

**Comment by Magnus-G** [comment]
I usually just add `@include omega;` for the last item to prevent it from falling to the row below, using something like `[name-of-element]:last-of-type`.

You can post your code if you want me to take a look!

**Comment by fabriziotappero** [comment]
Hi,
OK, I have tried your proposed solution:

.card
  @include span-columns(4)
  &:last-of-type
    @include omega

It does not work because the last-of-type is not the last element in the
raw (for a given screen size) but the last element inside card.... I cannot
think about any way to target the last element of the raw.
https://github.com/fabriziotappero/freerangefactory.org/blob/gh-pages/index.html

any idea?

fabrizio

**Comment by Magnus-G** [comment]
Ah, now I see what you're trying to do.
Use this code for `.card`:

```
  @include span-columns(4);
  @include omega(3n);
```

and make sure there is no `margin` set for `.card`. Neat will take care of the margins. Also make sure that there are no flexbox stylings left in `.card` or `.cards`

**Comment by fabriziotappero** [comment]
Hi,
yes, what you suggest is great and I have already implemented it and works
great.

The problem is that you want those cards to span different columns
according to the screen size and I do not understand how to make omega to
target always the last cards of the raw. Hence the original flex solution.
Would you like to do s codepen example?
