### ISSUE TITLE
Mobile sub menus do not toggle to hidden

### ISSUE THREAD

**Issue by pixeljitsu** [thoughtbot/refills#271]
When viewed on a phone, once you select a submenu it remains open and does not toggle to hidden if you click the parent again.

This is confusing, especially for complex menus.  Are there any menu examples where the submenus slide in from the right at each level ala F5?

I would really like to see a more robust mobile menu system, otherwise I've no quibbles at all.

**Comment by Magnus-G** [comment]
@pixeljitsu you are right. The menus are still a bit odd. We'll look into it. Please send a PR if you come up with anything!

**Comment by pixeljitsu** [comment]
Have a look at this: http://osvaldas.info/drop-down-navigation-responsive-and-touch-friendly

**Comment by Magnus-G** [comment]
@pixeljitsu would you be able to create a PR for this? Looks interesting!

**Comment by bpliske** [comment]
Any fix on this? I'd love to use these set of tools at our company, but it seems like when I place code on my project, unlike your examples, the navigation menu begins by staying open at phone width.

I realize I could place my own media queries, but my initial guess was that I somehow left out a step in your process. After all, the examples are working.  Thoughts?

**Comment by acandael** [comment]
I'm having the same issue, the mobile menu bar stays open and can't be toggled to hidden:

http://www.anthonycandaele.com

my Github repo:

https://github.com/acandael/myblog2

the Javascript for the mobile menu is at:

https://github.com/acandael/myblog2/blob/master/source/javascripts/_nav.js

thanks for your help,

Anthony

**Comment by COLABORATI** [comment]
Menu should not depend on JS.

**Comment by ricsmo** [comment]
Load jQuery like they do on the Refills examples page. If you check your console you'll see that you're getting an error that $ is not defined. I had the same issue and just solved it.

**Comment by tysongach** [comment]
I’m closing this as we are focusing our efforts on a [new, rewritten Refills library](https://github.com/thoughtbot/refills/projects) with a focus on accessibility and removal of grid and visual opinion for components. You can see a preview of the work here: http://refills.netlify.com/
