### ISSUE TITLE
Bourbon refill accordion/tab link ploblem

### ISSUE THREAD

**Issue by fabriziotappero** [thoughtbot/refills#284]
Hi,
I've implemented a simple accordion/tab taken from here
http://refills.bourbon.io/

Here is some code:
https://github.com/fabriziotappero/freerangefactory.org/blob/gh-pages/shop.html
all css here
https://github.com/fabriziotappero/freerangefactory.org/blob/gh-pages/css/main.sass
Here a working site
http://fabriziotappero.github.io/freerangefactory.org/shop.html

Any link inside a second tab leads to an empty screen.... the href is correctly parsed ny the jekyll markdown engine. I really dont know what is going on... maybe the refill JS?
Any help is greatly appreciated.

Cheers
Fabrizio

**Comment by Magnus-G** [comment]
@fabriziotappero this is strange. I see that it breaks on your site but I can't replicate it locally. When I try the following code (link in a second tab body) it seems to work. If you place the link directly in your code like this, without the handlebar partial, does it work? Just to try.

```
<ul class="accordion-tabs">
  <li class="tab-header-and-content">
    <a href="" class="tab-link is-active">Description</a>
    <div class="tab-content">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque ad sapiente, tempora cupiditate voluptas ullam molestiae praesentium, quisquam in voluptate tempore harum aut distinctio voluptatibus nostrum. Dolore quae, itaque optio!</p>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="" class="tab-link">Specifications</a>
    <div class="tab-content">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque ad sapiente, tempora cupiditate voluptas ullam molestiae praesentium, quisquam in voluptate tempore harum aut distinctio voluptatibus nostrum. Dolore quae, itaque optio!</p>

      <a href="http://dn.se">sdfsdf</a>
      
    </div>
  </li>
</ul>
```

**Comment by fabriziotappero** [comment]
Dear Magnum,
I totally apologize for the massive delay in replying to you on this matter
but I think you might interested in this bug you could not replicate.

As you can see, in your code, from the line:
 $('.accordion-tabs').on('click', 'li > a', function(event) {
you target the tab link but all internal links as well. This cause the
problem I mentioned. I think it would be better (but prefer to check with
you) to actually target only the tab header link using instead:
$('.accordion-tabs').on('click', 'li > a.tab-link', function(event) {

this has fixed my problem.

Could you please tell me your opinion.

cheers
Fabrizio




// shop item tabs styling
$(document).ready(function () {
  $('.accordion-tabs').each(function(index) {

$(this).children('li').first().children('a').addClass('is-active').next().addClass('is-open').show();

  });

  // this correction was necessary to prevent the mulfunciton of links
  // placed inside the tab space.
  //$('.accordion-tabs').on('click', 'li > a', function(event) {
  $('.accordion-tabs').on('click', 'li > a.tab-link', function(event) {
    if (!$(this).hasClass('is-active')) {
      event.preventDefault();
      console.log("bingo");
      var accordionTabs = $(this).closest('.accordion-tabs');
      accordionTabs.find('.is-open').removeClass('is-open').hide();

      $(this).next().toggleClass('is-open').toggle();
      accordionTabs.find('.is-active').removeClass('is-active');
      $(this).addClass('is-active');
    } else {
      event.preventDefault();
    }
  });
});



--
Fabrizio Tappero


2015-04-10 14:55 GMT+02:00 Magnus <notifications@github.com>:
