### ISSUE TITLE
Bourbon refill accordion/tab font size problem

### ISSUE THREAD

**Issue by fabriziotappero** [thoughtbot/refills#285]
the Bourbon Refill accordion tab snippet here:
http://refills.bourbon.io/

does not seem to respond to a media font resize code like this one:

  body
    p
      @include media(max-width 550px)
        font-size: 0.93em

Specifically, the fist tab respond well but any other (non visible tab) seems to be ignoring to font resizing. 

Example here (just resize to 500px width or less):
http://fabriziotappero.github.io/freerangefactory.org/shop.html

**Comment by Magnus-G** [comment]
@fabriziotappero if are you trying to target the tab links they are `<a>` tags. Try adding your rule to the `.tab-link` selector in the SCSS. Does that work?

```
  .tab-link {
    font-size: 3px;

    @include media($tab-mode) {
      font-size: 1em;
    }
```

**Comment by fabriziotappero** [comment]
Hello,
I am not referring to the tab link but to the text inside the body. Live example here:
http://fabriziotappero.github.io/freerangefactory.org/shop.html

in the shop section, if you resize the window so that it gets very small, only the text in the front tab is resized.

**Comment by Magnus-G** [comment]
@fabriziotappero I see what you mean. Unfortunately I can't recreate it locally. It works fine here. Could it have something to do with how you structure your files or the backend of your app? Have you tried building it outside of the app and check if it works in vanilla mode? If you can get that working maybe you can find a way to get it into your code step by step. Good luck! I'm closing this for now but let me know if you have any other questions.
