### ISSUE TITLE
Remove assets links from scss

### ISSUE THREAD

**Issue by Bogdaan** [thoughtbot/refills#287]
Files:
* refills/_device.scss
* refills/_grid-items.scss
* refills/_hero.scss
* refills/_hover-tile-animation.scss
* refills/_parallax.scss
* refills/_side-image.scss
* refills/_texture-legend.scss
* refills/_textures.scss

Contain links to "https://raw.githubusercontent.com/thoughtbot/refills/master/source/...".
But i need distribute assets ower CDN. How can i do that?

**Comment by tysongach** [comment]
You don’t have to use our assets, you can create your own. In fact, I would encourage you to create your own. Think of these just as starting points…

**Comment by tysongach** [comment]
@Bogdaan Does that make sense?

**Comment by Bogdaan** [comment]
@tysongach  Yes, but i use this sources and some elements for prototypes (like bootstrap, but with semantical grid).
And sometimes github hosts is "not available".

**Comment by tysongach** [comment]
We have no control over when GitHub goes down and these assets are not meant to be permanent. If you need distribution over a CDN, you can swap our assets with your own and have full control.
