### ISSUE TITLE
Modal not closing

### ISSUE THREAD

**Issue by Zurc** [thoughtbot/refills#288]
Hi, good day to you!

I was looking at refills' website and its components (http://refills.bourbon.io/components/)
The modal is not closing when clicking on close icon (only clicking outside the modal)

just that.
Cheers

**Comment by jme783** [comment]
+1, just noticed this today.

**Comment by jme783** [comment]
There seems to be a race condition, as when putting a timeout on this code, the modal closes:

**Comment by parker0phil** [comment]
+1 This causes pretty major issues on mobile (Android Chrome for me) as you can't click outside the modal to dismiss... have to reload page or navigate away :o(

**Comment by lperiodbose** [comment]
I was able to fix it by simply removing .modal-close from the .on("click") statement cited above.

Since .modal-close is a label for the checkbox, clicking .modal-close triggers $("#modal-1").on("change") without any further action, if I'm correct.

**Comment by Magnus-G** [comment]
@Zurc @jme783 @parker0phil @lperiodbose this should be fixed by changing

`<label class="modal-close" for="modal-1"></label>`

to 

`<div class="modal-close" for="modal-1"></div>`

I'm updating it on the site now.

**Comment by jme783** [comment]
:+1: thanks for checking this out
