### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by acandael** [thoughtbot/refills#289]
Hi,

I implemented the javascript for the unstyled navigation menu:

    <script>
      $(document).ready(function() {
     var menuToggle = $('#js-mobile-menu').unbind();
     $('#js-navigation-menu').removeClass("show");

     menuToggle.on('click', function(e) {
       e.preventDefault();
       $('#js-navigation-menu').slideToggle(function(){
          if($('#js-navigation-menu').is(':hidden')) {
           $('#js-navigation-menu').removeAttr('style');
           }
          });
        });
      });
    </script>

But when I look with Google Web Inspector I see this error in the console

    Uncaught ReferenceError: $ is not defined

greetings,

Anthony

**Comment by Magnus-G** [comment]
@acandael I've been trying to recreate this bug without success. Is your jQuery set up correctly? Does the nav work when you look at it in mobile size, i.e. does the animating menu work?

**Comment by Magnus-G** [comment]
@acandael closing this. Let me know if you still have an issue with this and we'll look into it.
