### ISSUE TITLE
Turning Refills into Sass library

### ISSUE THREAD

**Issue by mdotasia** [thoughtbot/refills#291]
Do you have any plans to turn Refills into a Sass library? I wonder if there is a way of including Refills components other than copy past. With a Sass library it would be easier to benefit from component updates.

**Comment by Magnus-G** [comment]
Hi @mdotasia, does the gem generator help you with this? Take a look at the Readme page and see if that's what you're looking for. We were discussing turning the components and patterns into mixins but decided that it wouldn't make much sense since the user *should* tweak the refills files.

**Comment by mdotasia** [comment]
After playing with the Refills, I realize that indeed I tweak the HTML and Sass of Refill components quite a bit. The only thing somewhat stable are the JavaScripts. But even there I change IDs. I probably need to drop the Bootstrap mindset of drop-in components.
