### ISSUE TITLE
Seach Tools is missing coffee

### ISSUE THREAD

**Issue by cllns** [thoughtbot/refills#293]
This file is currently empty: https://github.com/thoughtbot/refills/blob/master/source/javascripts/refills/coffeescript/search_tools.coffee

So if you click "Copy CoffeeScript" on http://refills.bourbon.io/ nothing happens (well... Firefox and Safari do nothing, Chrome lets your clipboard be set to nothing at all)

I tried removing that file, but it doesn't help, because https://github.com/thoughtbot/refills/blob/master/source/_snippet.html.erb hardcodes the link. We could try to generate that button only if the file exists, but it seems like it's not worth it's if only one missing CoffeeScript.

Does anyone have the CoffeeScript for that file? Or, if it doesn't exist, can someone write it?

**Comment by Magnus-G** [comment]
Hm, that file should have been automatically rendered. @teoljungberg do you know what happened there?

**Comment by teoljungberg** [comment]
@Magnus-G currently we need to generate the coffeescript ad-hoc with `rake coffee`. How would you feel with just having that being apart of the `publish` task instead?

**Comment by Magnus-G** [comment]
@teoljungberg I think that would make sense. Any reason why it wouldn't?

**Comment by tysongach** [comment]
I’m closing this as we are focusing our efforts on a [new, rewritten Refills library](https://github.com/thoughtbot/refills/projects) with a focus on accessibility and removal of grid and visual opinion for components. You can see a preview of the work here: http://refills.netlify.com/

Existing components and patterns from the 0.2.0 release will be provided as-is (no longer maintained) until the new version is released.
