### ISSUE TITLE
Possibly inconsistent use of breakpoint names in _navigation.scss

### ISSUE THREAD

**Issue by thebenedict** [thoughtbot/refills#295]
I noticed that `_navigation.scss` defines `$horizontal-bar-mode: $large-screen;`, but then in 4 places (lines 149, 184, 269 and 312) uses `$large-screen` directly, so changing the breakpoint requires 5 edits. Is this intentional? Happy to make a quick pull request if helpful.

**Comment by Magnus-G** [comment]
@thebenedict good catch! I'll take a look at this
