### ISSUE TITLE
Could not find generator 'refills:list'

### ISSUE THREAD

**Issue by ianejames** [thoughtbot/refills#296]
After installation, issuing `rails generate refills:list` returns:

<pre><samp>Could not find generator 'refills:list'. Maybe you meant 'devise:erb' or 'devise:views' or 'devise'
Run `rails generate --help` for more options.
</samp></pre>

The Refills generators aren't included in the list of generators from `rails generate --help`:

<pre><samp>Usage: rails generate GENERATOR [args] [options]

General options:
  -h, [--help]     # Print generator's options and usage
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -q, [--quiet]    # Suppress status output

Please choose a generator below.

Rails:
  assets
  controller
  generator
  helper
  integration_test
  jbuilder
  job
  mailer
  migration
  model
  resource
  responders_controller
  scaffold
  scaffold_controller
  task

ActiveRecord:
  active_record:devise

Coffee:
  coffee:assets

Devise:
  devise
  devise:controllers
  devise:install
  devise:views

Js:
  js:assets

Mongoid:
  mongoid:devise

Responders:
  responders:install

TestUnit:
  test_unit:generator
  test_unit:job
  test_unit:plugin
</samp></pre>

Environment

* Mac OS X 10.10.3
* rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
* ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
* rubygems 2.4.6
* Rails 4.2.1

**Comment by ianejames** [comment]
I just tried again, and the generator now seems to work. I'm not sure what fixed it -- there was a restart involved which would have reloaded pretty much everything. Sorry I don't have more information, but this probably wasn't a problem with Refills anyway.

**Comment by teoljungberg** [comment]
Glad to hear it sorted itself out @ianejames, I'll close this
