### ISSUE TITLE
Cards custom image issue

### ISSUE THREAD

**Issue by Doppelganger113** [thoughtbot/refills#300]
When using a custom image i don't get the same hover effect. Tried a couple of things, including the changing of z index, but with no luck. When i change back to the original, everything works fine.

**Comment by Magnus-G** [comment]
@Doppelganger113 are your images slightly semi-transparent? The ones in the example are and that's why the color change is visible on hover.

**Comment by Doppelganger113** [comment]
@Magnus-G 
Then i might have tried with faulty ones from google images. Anyway, if that is the case, one would always have to change their pictures to be semi-transparent. Wouldn't it be easier to put a semi transparent layer in front of the picture and toggle him ? Not the other way around.

**Comment by Magnus-G** [comment]
@Doppelganger113 you are probably right! If you get it working, feel free to open a PR here and we might turn it into that instead!

**Comment by Magnus-G** [comment]
Merged
