### ISSUE TITLE
Textures not working in Firefox

### ISSUE THREAD

**Issue by selfagency** [thoughtbot/refills#301]
Hi,

For some reason, the textures refill is working fine for me in Chrome and Safari, but textures aren't rendering in Firefox. 

Here's Chrome's rendered CSS:
![screenshot 2015-05-04 19 57 11](https://cloud.githubusercontent.com/assets/2541728/7465078/3c7352d2-f298-11e4-955e-257d42ca63fd.png)

Here's Firefox's rendered CSS of the same element:
![screenshot 2015-05-04 19 59 17](https://cloud.githubusercontent.com/assets/2541728/7465074/36926f9c-f298-11e4-80c0-dd155c221497.png)

Any thoughts?

Thanks.

**Comment by Magnus-G** [comment]
@selfagency seems to work here. Have you tried just putting the code from Refills straight into your project and see if that works?

Maybe it's the `background-color` that you've added?

If I start a vanilla project and use the snippet from Refills it works. Maybe you can try doing that and build the footer from that end?

**Comment by selfagency** [comment]
removing the background-color didn't help. 

and i am use the code from refills straight in my project. all i did was change the colors and texture number.

**Comment by Magnus-G** [comment]
@selfagency I'm not sure what's going on there but have you tried changing colors, texture numbers and invertion? Some textures don't show up well with some colors and you then have to invert them. The 0 or 1 at the end of the mixin call.

**Comment by Magnus-G** [comment]
@selfagency I will close this for now. Feel free to ping us again if you run into more trouble.
