### ISSUE TITLE
Dropdown Duplicate Refills

### ISSUE THREAD

**Issue by ericsonluciano** [thoughtbot/refills#302]
Hello how i can solve this issue i made a multiple dropdown around 7 times and all of that is almost same css same code but different list of answer when i click one buttons all dropdown-menu show. i try to use $(this) at javascript but it's failed. any idea? Thank you

**Comment by Magnus-G** [comment]
@ericsonluciano I only know the dirty version of doing this; adding a specific class to each dropdown. But I'd be interested to hear how a developer would solve this. What do you think @teoljungberg?

**Comment by jbender** [comment]
@ericsonluciano I had the same problem, here's the coffeescript that I used, should be easy enough to convert to JS if you prefer:

    $(document).ready ->
      $(".dropdown-button").click ->
        $button = $(this)
        $menu = $button.siblings('.dropdown-menu')

        $menu.toggleClass "show-menu"
        $menu.children('li').click ->
          $menu.removeClass "show-menu"
          $button.html $(this).html()
          return

        return

      return

**Comment by Magnus-G** [comment]
Thanks @jbender this is not merged!
