### ISSUE TITLE
Modal window margin introduce scroll bar on Chrome under Windows 7

### ISSUE THREAD

**Issue by fabriziotappero** [thoughtbot/refills#312]
On Google Chrome Version 43.0.2357 on Windows 7 the current modal window has an unwanted scrollbar.

thanks

**Comment by Magnus-G** [comment]
@fabriziotappero thanks for catching this. Can you post an image of what this looks like?

**Comment by tysongach** [comment]
@fabriziotappero Any update? Can you post a screenshot?

**Comment by fabriziotappero** [comment]
Hi Tyson,
I actually solved this issue by doing something I cannot really remember.

Almost one year has passed and I apologize if I did not really keep up with
this issue.

Regards
Fabrizio

**Comment by tysongach** [comment]
@fabriziotappero No worries; thanks for the update!
