### ISSUE TITLE
React components ?

### ISSUE THREAD

**Issue by borisrorsvort** [thoughtbot/refills#314]
Do you have any plans to propose a react component version refills ? Coupled with react-gem and the isomorphic prerender helper, that'd be awesome :)

**Comment by kaishin** [comment]
@borisrorsvort We're not very familiar with React, so it's probably not happening unless someone else does it. We'd be happy to link to it if that happens.

@Magnus-G any thoughts?

**Comment by graysonwright** [comment]
@thoughtbot/react - thoughts?

I agree - that would be a really cool way to use Refills. I'm a bit full on my investment time currently, so I don't think I can put the time into it. Any takers?

**Comment by Magnus-G** [comment]
@borisrorsvort @kaishin @graysonwright sounds interesting! I guess it's a question of building it and then being able to maintain it. I'd suggest building a couple of components to see if it makes sense. Would anyone be interested in doing that?

**Comment by borisrorsvort** [comment]
Hi, nice to see some enthousiasm :) 

@Magnus-G you're right, we should start by making a pov.

I just started using react-rails on a project and some stuff are still bugging me regarding the view helper that fetches a components. Basically you can't pass a block unless you make a custom helper (like here https://github.com/reactjs/react-rails/pull/166) that takes advantage of a 'dangerous' feature in react where you can pass raw html as a prop (explained here https://facebook.github.io/react/tips/dangerously-set-inner-html.html).

That means you either pass a full json presenter or use that __html feature. But then you have to make sure your html is safe.

That means in practice that for complex components you can't nest components from the rails view but only  use a controllerView to set it up (dont know if i'm clear ^^). 

Maybe for our case here, it would be best to start with jsx only components except for some where you can just pass text or a config (like the badges)

**Comment by lulato** [comment]
I am working on a few patterns from Refills make into React, but Im also a newbie.

**Comment by lulato** [comment]
A lot of the of the components are transformed changing.
``` class
```
into 
```
className
```
and making sure you close the image tag
```
<img src="..." />
```
The hard part for me is the logic.
https://gist.github.com/lulato/1c3946ca8986ee96a053

**Comment by lulato** [comment]
So I made another one. This time the hero.
https://gist.github.com/lulato/f02055a671ea6e9db9b1

**Comment by Magnus-G** [comment]
@lulato very nice. I see that you use variables in the hero component, making it easier to read. Maybe that would be a good thing for the nav component too?

**Comment by lulato** [comment]
@Magnus-G I would totally be willing to help out transform "Refills" into if you guys make a repo.

**Comment by borisrorsvort** [comment]
:+1:

**Comment by Magnus-G** [comment]
@lulato that's great! I'd suggest you make a public repo and put the components there. It's tricky for us to start repos that we are not the primary maintainers of. If it works out well we'll definitely be interested in working with you on that repo!

**Comment by Magnus-G** [comment]
Closing this for now.

**Comment by stephanedaviet** [comment]
Any news on this? React have gained some momentum now, and it would be great to have Refills as React components.

**Comment by graysonwright** [comment]
@stephanedaviet I've been thinking for a while about building a public library of React components, with tooling to easily install and use them in any project. It sounds like Refills would be a great starting point for it.

I set up an empty repo, [assembleapp/react-component-library](https://github.com/assembleapp/react-component-library), and an [open issue](https://github.com/assembleapp/react-component-library/issues/1). Want to start the conversation there?

**Comment by stephanedaviet** [comment]
Great, let's go other there to follow this conversation then.
