### ISSUE TITLE
rake coffee task not working

### ISSUE THREAD

**Issue by codebryo** [thoughtbot/refills#317]
I wanted to contribute to this project and go over a bunch of scripts but somehow the `rake coffee` task always screws up. I tried to install `js2coffee` globally, tinkered around with the script and stuff but could not get it to work properly. My understanding of rake is a little limited but thats the only thing holding me back from contributing to the main JS code. 
Did I do something wrong or did I miss something in the contributor guide ?

**Comment by Magnus-G** [comment]
@teoljungberg any input on this one?

**Comment by teoljungberg** [comment]
Sorry for taking so long getting back to you.

I updated the contribution document in https://github.com/thoughtbot/refills/pull/328.
Does that clarify what you had problems with?

**Comment by tysongach** [comment]
@codebryo Any update?
