### ISSUE TITLE
Flex Boxes dont print correctly on IE

### ISSUE THREAD

**Issue by tollrakesh** [thoughtbot/refills#319]
When there are more than 7 flex boxes, they dont print (Anything that overflows to the 2nd page doesnt show up) correctly on IE 11 (Didnt try on earlier versions). It renders the boxes correctly on the browser window.

It works on Chrome and Firefox though.

**Comment by Magnus-G** [comment]
Hi @tollrakesh, it seems to work here:

![image](https://cloud.githubusercontent.com/assets/2095625/9135874/123467f8-3d12-11e5-9ba6-671bb81e73f8.png)

Could you clarify a bit where you run into this issue and how it looks? What do you mean with 2nd page?

**Comment by Magnus-G** [comment]
Closing this for now. @tollrakesh please open it up again if it's still an issue.
