### ISSUE TITLE
Switch stops working in IE11 when hidden input element is added before the checkbox input element

### ISSUE THREAD

**Issue by timmliu** [thoughtbot/refills#321]
The switch component stops working in IE11 when `<input type="hidden">` is added into the label-switch element, like so: 

```
<label class="label-switch">
  <input type="hidden">
  <input type="checkbox">
  <div class="checkbox"></div>
</label>
```

Clicking will not trigger a click event, the switch will not change/flip, and the checkbox value will also not change. 

This is not so much an issue with the current implementation as it is a feature request, since hidden inputs should be pretty common in forms.

**Comment by Magnus-G** [comment]
Hi @timmliu, yeah this one is interesting. Not quite sure why that `hidden` field breaks the switch. It seems to work if you put the `hidden` outside of the switch. Would that be an option or does it need to be on the inside?

**Comment by timmliu** [comment]
@Magnus-G Somehow the hidden input element is covering the regular checkbox input in ie11, like literally on top of it, so when you try to click the real input you are actually clicking the hidden input or something. I was able to circumvent it by using javascript to trigger a click on the checkbox directly. 

I haven't tested with it outside. I think it would work.. but it is pretty typical for form helpers to generate a hidden input right before the regular input. See Rails built-in form helpers: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html, and this is the gem for Rails forms that I am using: https://github.com/plataformatec/simple_form. So ideally it would be on the inside.

**Comment by Magnus-G** [comment]
@timmliu yeah it doesn't seem like either `visibility: hidden` or `display: none` does anything to make it better.

**Comment by timmliu** [comment]
@Magnus-G yeah, not sure if there is much that can be done here. I thought about putting the hidden input after the checkbox input, but then the current css would need to be smart/updated because `+ .checkbox` depends on the checkbox input being next to the `.checkbox` div.

**Comment by Magnus-G** [comment]
@timmliu if you find a way change the css (and the markup) and make that work please let me know. Otherwise I guess we should put this on hold?

**Comment by timmliu** [comment]
@Magnus-G ok sounds good.

**Comment by Magnus-G** [comment]
Closing this for now.

**Comment by alanjudson** [comment]
I know why this is happening.  It's because ie11 doesn't like hidden type inside <label>:
```
<label class="label-switch">
  <input type="hidden">
  <input type="checkbox">
  <div class="checkbox"></div>
</label>
```
But it likes this.
```
<input type="checkbox">
<label>
  Some label text
  <input type="checkbox">
</label>
```

**Comment by sn3p** [comment]
Same problem here using Rails **[`check_box`](http://apidock.com/rails/ActionView/Helpers/FormHelper/check_box)**, which adds an auxiliary hidden field before the check box.
