### ISSUE TITLE
Pagination component doesn't show lighter background for active link

### ISSUE THREAD

**Issue by acandael** [thoughtbot/refills#322]
Hi,

For my Rails project, I implemented the Kaminary gem for pagination. I customized the view template, and implemented the Refills Pagination component.

This work well, but I have an issue with the active link in the paginator. The example of the Paginator component on the Refill site shows a lighter background for a selected - active - page. So one can see the wich page is selected in the paginator.

My implementation doesn't show a lighter background for the selected page in the Paginator component. I don't know what causes the issue, because the html is exactly the same as the example on the Refill site.

My implementation of the Refill Pagination component can be found here:
http://www.adlit.be/news

The repository for this website is at:
https://github.com/acandael/adlit-rails

Thanks for your help,

Anthony

**Comment by LimeBlast** [comment]
Hi, I've got a feeling that you've misread the CSS provided by the pagination refill.

I think that you've seen `&:active` and misinterpreted its purpose - this section of code is used when the link is in an *active* state, that is, currently being clicked - not for highlighting the active (or 'current') page.

As it stands currently, the pagination refill doesn't have any styling for the current page, but his is fairly simple to add.

First, [modify this line](https://github.com/acandael/adlit-rails/blob/master/app/views/kaminari/_page.html.erb#L10) to:

    <li class="<%= 'current' if page.current? %>">

This will cause the `current` class to appear on the relevant element in the pagination - but right now it doesn't have any styling, to fix this, add something like the following [above this line](https://github.com/acandael/adlit-rails/blob/master/app/assets/stylesheets/partials/_pagination.scss#L42):

    li.current a { background-color: green }

changing `green` for whatever colour you want.

I hope this helps.

**Comment by Magnus-G** [comment]
@acandael does @LimeBlast's answer get you what you need?

**Comment by Magnus-G** [comment]
@acandael, I'm closing this issue for now. Feel free to open it up if you have other concerns.

**Comment by Magnus-G** [comment]
@acandael, I'm closing this issue for now. Feel free to open it up if you have other concerns.
