### ISSUE TITLE
Animated progress bar not visible on browser width < 860px

### ISSUE THREAD

**Issue by talltorp** [thoughtbot/refills#326]
When I scale my browser window to a width below `860px`, the animated progress bar turns into a thin line.

![image](https://cloud.githubusercontent.com/assets/1172400/9515143/a9729a08-4c9f-11e5-8c3b-b05c3f37a9d8.png)

The behaviour is the same for Chrome, Firefox and Safari.
I am on a Mac.

**Comment by Magnus-G** [comment]
@talltorp Thanks! I have fixed this in this PR https://github.com/thoughtbot/refills/pull/327

The issue should only happen on the Refills site, not when you copy-paste the code!

**Comment by talltorp** [comment]
Thanks!
