### ISSUE TITLE
Class `more` on navigation doesn't more in versions of chrome >=46

### ISSUE THREAD

**Issue by DropsOfSerenity** [thoughtbot/refills#332]
The more class on the navigation refill dissapears in chrome >=46. I don't know the precise reason but adding `position:relative` to `ul.navigation` when bar is in horizontal mode fixes the issue.

I will make a pull request shortly and reference this issue.

**Comment by vmanera** [comment]
Can confirm this also occurs in chrome 45. The fix works, I hit my head against a wall trying to figure this one out.

**Comment by jimfrenette** [comment]
when will this be fixed for chrome >= 45 at http://refills.bourbon.io/#navigation
