### ISSUE TITLE
navigation does not render correctly

### ISSUE THREAD

**Issue by Yanchek99** [thoughtbot/refills#337]
Navigation refill styling does not render correctly, biggest differences can be seen in the search bar.

Also note that box-sizing mixin is deprecated and needs to be refactored to use box-sizing css un prefixed.

**Comment by Magnus-G** [comment]
Hi @Yanchek99, I am not sure what you are referring to here. Would you mind uploading a screenshot? Any specific browser you are using?

Thanks for the reminder about box-sizing!

**Comment by Yanchek99** [comment]
@Magnus-G I am really sorry, that was an awful bug report on my part.  I don't even remember how to recreate my issue, so I am going to close this.  If I happen to recreate it later I will be sure to include screenshots and a more descriptive bug.  Again my apologies for the sloppy report, must have been in a rush.
