### ISSUE TITLE
Search refill has deprecated warnings

### ISSUE THREAD

**Issue by IgorNadj** [thoughtbot/refills#338]
WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of theme/scss/bourbon/_bourbon-deprecated-upcoming.scss
	from line 19 of theme/scss/refills/_search-bar.scss

WARNING: The button mixin is deprecated and will be removed in the next major version release
	on line 64 of theme/scss/bourbon/_bourbon-deprecated-upcoming.scss
	from line 35 of theme/scss/refills/_search-bar.scss

Just FYI - thanks!

**Comment by Magnus-G** [comment]
Thanks @IgorNadj this has now been fixed!
