### ISSUE TITLE
Errors using refills

### ISSUE THREAD

**Issue by anartfulscience** [thoughtbot/refills#340]
Hello,

I wondered of you could help. I've installed both neat and bourbon via npm and it works ok until I try and use refills. I pasted in the scss and html for the "switch" component but I get the following errors.

 143:18  required parameter $height is missing in call to mixin size
Details:
    formatted: Error: required parameter $height is missing in call to mixin size

My setup is 
@import "../../node_modules/bourbon";
@import "../../node_modules/neat";

The above is before any of my project scss.

Many thanks, Stephen

**Comment by Magnus-G** [comment]
@anartfulscience I am not able to recreate this. 
Have you tried the switch in a vanilla project with bourbon/neat installed without npm?

@tysongach do you know if this is an issue related to Bourbon versions?

**Comment by anartfulscience** [comment]
Hello,

Thanks for the reply. I believe it was a duplicate mixin so it threw everything out. It seems to be working ok now.

Cheers, Stephen
