### ISSUE TITLE
Bug in black navigation bar on refills demo page, causes primary menu items to disappear

### ISSUE THREAD

**Issue by piratebroadcast** [thoughtbot/refills#346]
On the refills demo page at http://refills.bourbon.io/, if you scroll down to the black navigation bar with the search box and expand the "more" section by hovering over it, once you hover over the subitems in the "more list", it causes most of the primary menu items to disappear. Screenshot of bug in action: http://i.imgur.com/kgx3PAy.png

**Comment by joshuaogle** [comment]
@piratebroadcast I've tried a few browsers and haven't been able to replicate the problem. What browser and OS were you in?

**Comment by piratebroadcast** [comment]
Chrome Version 46.0.2490.86 (64-bit), and OSX Yosemite 10.10.5.

On Sun, Nov 29, 2015 at 8:59 PM, Joshua Ogle <notifications@github.com>
wrote:

> @piratebroadcast <https://github.com/piratebroadcast> I've tried a few
> browsers and haven't been able to replicate the problem. What browser and
> OS were you in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thoughtbot/refills/issues/346#issuecomment-160497114>.
>



-- 
Jesse Waites
JesseWaites.com

**Comment by tysongach** [comment]
I’m also unable to replicate this in Chrome, Firefox and Safari. Closing; let us know if this issue is persisting.
