### ISSUE TITLE
Breadcrumb border problem

### ISSUE THREAD

**Issue by gocart** [thoughtbot/refills#347]
The border-left:0; on the <a> tag just under the breadcrumb class is being overwritten by the border that follows it.

![screenshot 2015-11-29 23 02 00](https://cloud.githubusercontent.com/assets/1082109/11463809/39c85a6a-96ed-11e5-8cbe-f00ec7371add.png)

![screenshot 2015-11-29 23 00 32](https://cloud.githubusercontent.com/assets/1082109/11463796/03899482-96ed-11e5-8f3e-bcfca4d80866.png)

**Comment by Magnus-G** [comment]
@gocart in which browser and version is this?

**Comment by gocart** [comment]
Chrome 46.0.2490.86 (64-bit)
What's actually happening though is that the border-left:0 is being generated by Sass before the border: $breadcrumb-border;  that follows it. 

The final rendered CSS comes out like this.

```
a {
   background-color:white;
   border-left:0;
   border: 1px solid gainsboro;
   ...
```

if the styles were written as follows it would work

```
a {
    background-color: $breadcrumb-background;
    border: $breadcrumb-border;
    border-left: 0;
    ...
```

**Comment by tysongach** [comment]
@gocart Yep, looks like a bug. If we switch the order of [Lines `26` & `27`](https://github.com/thoughtbot/refills/blob/master/source/stylesheets/refills/_breadcrumbs.scss#L26-L27) in `_breadcrumbs.scss` it should resolve the issue. Would you be up for submitting a PR to do that?
