### ISSUE TITLE
tooltip arrow is offset

### ISSUE THREAD

**Issue by egladman** [thoughtbot/refills#351]
This is in reference to [tooltip component](http://refills.bourbon.io/components/#tooltip)

There is space between the arrow and the tooltip's content. If this is indeed unexpected behavior I'd be more than willing to submit a fix. I was expecting the refill to behave similarly to [tipsy.sass](http://eli.gladman.xyz/tipsy.sass/).

![2016-01-05-00 59 00](https://cloud.githubusercontent.com/assets/8713153/12108692/7f382a04-b348-11e5-8763-18f31e732371.png)

**Comment by tysongach** [comment]
@egladman What browser are you seeing this in?

**Comment by Magnus-G** [comment]
@egladman it's funny how even tipsy has this issue in Firefox:

![image](https://cloud.githubusercontent.com/assets/2095625/12354151/4fc08452-bb94-11e5-9a9e-453b6d6e4805.png)

it is a cross-browser problem that forces the components to jump around like this. If you find a fix, please let us know!

**Comment by tysongach** [comment]
I’m not sure we have an action to take here; seems to be an issue with Firefox, though I can’t replicate it.
