### ISSUE TITLE
Center navigation: missing various mixins, why?

### ISSUE THREAD

**Issue by guidstah** [thoughtbot/refills#353]
Hi,

I'm trying to get my head arround this, the example on centered navigation uses various mixins like media(), outer-container(), etc. that are not included in bourbon or in bitters.

I followed the requirements and have Sass 3.4.2. 
Installed Bourbon in a Sage project with bower install --save bourbon
Installed Bitters with gem, this created base folder in stylesheets
Added the bitters base.scss to the project

For example, when running gulp the output is:
>assets/styles/layouts/_header.scss
>Error: no mixin named outer-container
>
>       Backtrace:
>       	assets/styles/layouts/_header.scss:70
>        on line 70 of assets/styles/layouts/_header.scss
>     @include outer-container;
>   -------------^

Any ideas what I'm doing wrong here?

**Comment by tysongach** [comment]
@guidstah These mixins are from Neat, which is also [a requirement](https://github.com/thoughtbot/refills#requirements). Try installing that, as well, and see if that resolves your issue!
