### ISSUE TITLE
Usage of deprecated inline-block mixin

### ISSUE THREAD

**Issue by bendobos** [thoughtbot/refills#357]
I am getting this error:
```WARNING: The inline-block mixin is deprecated and will be removed in the next major version release```

The mixin is used in the accordion-tabs Refill. This is not yet a pressing issue but how do I get rid of this mixin? Just removing it breaks the tabs.

**Comment by tysongach** [comment]
@bendobos This mixin is coming from Bourbon, and it’s been deprecated within that library. You should be able to simply swap the mixin with `display: inline-block;`, like so:

```diff
- @include inline-block;
+ display: inline-block;
```

**Comment by tysongach** [comment]
With https://github.com/thoughtbot/refills/commit/061a6cb5aa023126bec1eef024844eb74603c9cb, this mixin is no longer being used in the source.
