### ISSUE TITLE
footer-2 (Sticky Footer) display property

### ISSUE THREAD

**Issue by Judahmeek** [thoughtbot/refills#361]
Currently, footer-2's display value is `inline-block`. Even with `html, body { margin: 0; }`, this still results in a line at the bottom of the page due to inline-block's whitespace "feature".

![image](https://cloud.githubusercontent.com/assets/8206741/13797609/deef7b34-eadc-11e5-8a60-76aba5d5390c.png)

So why isn't footer-2's display value simply `block`?

**Comment by Judahmeek** [comment]
Granted, if you only change the example footer's display value to `block`, it collapses, but that's only because the example footer is not assigned the height that is set in the commented out SCSS below.

![image](https://cloud.githubusercontent.com/assets/8206741/13797744/eab71188-eadd-11e5-9318-634d2b5b28c1.png)

**Comment by Magnus-G** [comment]
merged
