### ISSUE TITLE
Centered navigation submenus are cut off

### ISSUE THREAD

**Issue by lorentrogers** [thoughtbot/refills#365]
With smaller viewports, it looks like the subnavs go off screen. I would have expected all the elements to be shown within the breakpoint?

![screenshot - 03172016 - 02 24 18 pm](https://cloud.githubusercontent.com/assets/1090824/13858174/d635618e-ec53-11e5-8f66-a20249c8cf99.png)

**Comment by Magnus-G** [comment]
@lorentrogers this is a good catch. Looking into it.

**Comment by Magnus-G** [comment]
PR https://github.com/thoughtbot/refills/pull/373

**Comment by Magnus-G** [comment]
Merged
