### ISSUE TITLE
Drag on side menu

### ISSUE THREAD

**Issue by lorentrogers** [thoughtbot/refills#366]
I'm not sure if this was the intended behavior, but when I drag on the side menu of the http://refills.bourbon.io/ nav, it drags the whole page. Figured I'd point it out in case it was unintentional.

Unfortunately, you can't see my mouse in this recording, but I'm dragging vertically on the left nav, and it scrolls the page under it.

![recorded](https://cloud.githubusercontent.com/assets/1090824/13858465/2f7007d0-ec55-11e5-9370-6dd8c7e27f96.gif)

**Comment by Magnus-G** [comment]
@lorentrogers this is intended! If you want the page to stick when the `side menu` is out I think it´s just a matter of where the `side menu` markup is placed.
