### ISSUE TITLE
Modal scss uses `columns` mixin which is removed from bourbon 5.0.0

### ISSUE THREAD

**Issue by jaredmoody** [thoughtbot/refills#369]

**Comment by tysongach** [comment]
@jaredmoody Hi! Yes, The current version of Refills is not yet compatible with Bourbon 5. We’ll make a sweep soon-ish to make them compatible.

**Comment by tysongach** [comment]
@jaredmoody FYI: I’ve started working on Bourbon 5 compatibility here: https://github.com/thoughtbot/refills/tree/tg-bourbon-5

**Comment by tysongach** [comment]
Usage of `columns` has been removed in 4e6693f1a38db3597e1321b44c3d5b15a88872b0.

I’ve also opened a PR to upgrade Refills to Bourbon 5: https://github.com/thoughtbot/refills/pull/375
