### ISSUE TITLE
Does Refills depend on Rails? Would like to use it with NPM, Webpack, and React.

### ISSUE THREAD

**Issue by AustinWinstanley** [thoughtbot/refills#371]

**Comment by tysongach** [comment]
@AustinWinstanley Hi! No, it does not directly depend on Rails; only Bourbon, Neat and Sass. That being said, Refills is available as a Ruby gem with a Rails generator which makes it very easy to place components within a Rails app. The slightly less straightforward way to install Refills components is to copy-paste from the website. At this time, we are not focused on installation or features around npm, webpack or React.
