### ISSUE TITLE
$refills-max-width; undefined

### ISSUE THREAD

**Issue by joggienl** [thoughtbot/refills#374]
Hello,

I was trying out the Hero Unit component. I noticed that there's a variable in there called "refills-max-with" which hasn't got a declaration. Looking somewhat further I also saw this variable being used at the Navigation component.

Is this correct or am I missing something out?

Thanks!

**Comment by opalepatrick** [comment]
I have this as well. Was there a solution/reason? Thanks

**Comment by joggienl** [comment]
I noticed it being defined in https://github.com/thoughtbot/refills/blob/master/source/stylesheets/_refills-variables.scss.

The suggested way to use refills in a non Ruby environment does not describe having this file or content somewhere in your project.

I think the variable should not be in the refill?

**Comment by Magnus-G** [comment]
@joggienl you are right! I'm removing it now and updating the hero a bit, right now.

**Comment by Magnus-G** [comment]
some proposed updates here: https://github.com/thoughtbot/refills/pull/378

**Comment by opalepatrick** [comment]
Excellent, thank you both!

**Comment by joggienl** [comment]
Thanks!

**Comment by nunofreitasbotelho** [comment]
What if you replace it by $max-width as stated on this neat mixin:
@mixin outer-container($local-max-width: $max-width)
