### ISSUE TITLE
JS error in navigation component

### ISSUE THREAD

**Issue by RopoMen** [thoughtbot/refills#376]
Hi,

I have using navigation component without "More" section, because I do not have any usage for that. But that will cause JS error 
```js
code.js:378 Uncaught TypeError: Cannot read property 'left' of undefined
```

that is caused by this section of code, which does not make any check whether the 'more' is actually element or null.
```js
  var more = document.getElementById("js-navigation-more");
  var windowWidth = $(window).width();
  var moreLeftSideToPageLeftSide = $(more).offset().left;
```

**Comment by Magnus-G** [comment]
@RopoMen thanks! Should be fixed here: https://github.com/thoughtbot/refills/pull/377
