### ISSUE TITLE
example request for refills flex side by side on mobile

### ISSUE THREAD

**Issue by tvmaly** [thoughtbot/refills#381]
Would it be possible to provide an example of a side by side grid item of flex box item similar to how the categories appear on http://www.slant.co/ in mobile?

When I view the refills examples, everything collapses to a single column.

**Comment by Magnus-G** [comment]
@tvmaly have you tried altering the 

`flex: 2 2 15em;`

value? If you make the 15em smaller you should get closer to getting two columns on small screens. I also recommend checking out this one in the Empties library: http://empties.bourbon.io/#grid

**Comment by tvmaly** [comment]
Thanks I will give this a try.  I was able to get the grid item side by side.

**Comment by Magnus-G** [comment]
@tvmaly great! Closing this for now.
