### ISSUE TITLE
'Navigation' bar not working

### ISSUE THREAD

**Issue by kivohin** [thoughtbot/refills#382]
In 'Patterns' the 'Navigation' component (not the 'Centered Navigation'), gives an error in its SCSS file when using in Rails. I have Bourbon 4.2.7 by the way. The error it gives is the following: Undefined variable: "$refills-max-width". So if I delete in line 30 of your code '($refills-max-width)' then the navigation bar will work.
![refillserror](https://cloud.githubusercontent.com/assets/17774060/15246228/64d90c90-190b-11e6-9ee6-d11ea46a528a.jpg)

**Comment by Magnus-G** [comment]
@kivohin thanks! Fixing this now. Just remove it and it should work.
