### ISSUE TITLE
Remove “unstyled” Refills

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/refills#389]
Now that we have [Empties](http://empties.bourbon.io/), it doesn’t make much sense to keep the [“unstyled” Refills](https://github.com/thoughtbot/refills/tree/master/source/stylesheets/refills/unstyled) around.

**Comment by HassenPy** [comment]
can i work on this?

**Comment by tysongach** [comment]
@HassenPy Absolutely! And thanks! Ping me if you have any questions.

**Comment by tysongach** [comment]
After digging in a bit more, these “Unstyled” Refills don’t necessarily mean that there is a styled version also; so we might be removed valid, useful patterns or components. Going to close for now, but I think the term “Unstyled” should go away at some point.
