### ISSUE TITLE
Components Dropdown CSS contains the invalid attribute overflow: show;

### ISSUE THREAD

**Issue by zeitlerc** [thoughtbot/refills#392]
The generated CSS for .dropdown .dropdown-menu contains the value "show" for overflow, which is not an a valid value.  The syntax for overflow is `overflow: visible|hidden|scroll|auto|initial|inherit;`.  The "show" value causes a Sass compile warning and the overflow attribute is ignored by the browser.

**Comment by tysongach** [comment]
@zeitlerc Thanks for letting us know! Would you be up for submitting a Pull Request to fix that?

**Comment by zeitlerc** [comment]
@tysongach Sure, it should be a simple fix.

**Comment by zeitlerc** [comment]
Shoot, didn't do my research.  This was already fixed on master #388 , but I was looking at a previous version.
