### ISSUE TITLE
refill samples and Chrome device toolbar

### ISSUE THREAD

**Issue by tvmaly** [thoughtbot/refills#393]
I do not think this is really an issues with refills, but it does affect the development.

I am using the latest Chrome browser on OSX version 51.0.2704.106   when I use the device toolbar to emulate a mobile phone, the display does not work correctly for the refills samples.  It was working correctly at the end of May.

It works correctly in the responsive emulation on Firefox, and one a chrome mobile browser on a phone the samples work correctly.  This is just something to be aware of.

**Comment by tysongach** [comment]
Just checked and it _seems_ fine. Emulators are always a bit funny; maybe they improved it (Chrome is up to v56 now). Also, emulators need a refresh of the page after enabling it!

👍
