### ISSUE TITLE
Button mixin removed in Bourbon 5 – modal still uses it.

### ISSUE THREAD

**Issue by haraldkrischner** [thoughtbot/refills#394]
According to the [changelog](https://github.com/thoughtbot/bourbon/blob/888e83a9f90a5d7d795e5ffa3ad035743a8d1393/CHANGELOG.md) of Bourbon 5 the button mixin was removed.

But the modal snippet still contains the call:
```
.modal-trigger {
      @include button(flat, $base-accent-color);
    padding: 0.8em 1em;
  }
```

**Comment by tysongach** [comment]
Hi @haraldkrischner! The `button` mixin was removed from the modal in June 2015: https://github.com/thoughtbot/refills/commit/a569c38e2a030330d51ce1f9521909dadc1b144f.

Are you possibly using an older version of Refills? Or where are you pulling that code from?

**Comment by haraldkrischner** [comment]
Hi Tyson, thanks for looking at this issue. You are right. I preferred to install it as a gem, but via that way you only get the last release not containing this change. With the current master everything works! Thanks againg!
