### ISSUE TITLE
hero refill background img

### ISSUE THREAD

**Issue by skshel123** [thoughtbot/refills#395]
I can't figure out how to get the hero unit to display correctly. All the other refill modules I import into my project work fine, it's just the hero unit. Any help would be greatly appreciated!

**Comment by whmii** [comment]
@skshel123 can you post a screenshot and/or code sample? that may help debug the issue.

**Comment by jaredmoody** [comment]
I'm getting an `Undefined mixin 'media'.` error when trying to use the hero refill out of the boxusing refills 0.2.0 and bourbon 5.0.0.beta6. Easy to work around, but doesn't look that that mixin is available any longer.

**Comment by whmii** [comment]
@jaredmoody try to open a new issue as I don't believe your issue is the same as @skshel123 's

Anywho, you ( @jaredmoody ) need to import Neat since the `@include media` mixin is a property of Neat, not bourbon or bitters.

**Comment by jaredmoody** [comment]
@whmii thanks, my bad.
