### ISSUE TITLE
Modal's stopPropagation disables child elements from performing additional js functions.

### ISSUE THREAD

**Issue by insidetheeye** [thoughtbot/refills#401]
I've instantiated [Clipboard.js](https://clipboardjs.com/) on an element inside a refills modal. The problem is, it's functionality is cancelled out by .modal-inner's stopPropagation when the modal is open. Has anyone encountered this issue? I've tried solving on my own and haven't been able to do so.

**Comment by tysongach** [comment]
I’m closing this as we are focusing our efforts on a [new, rewritten Refills library](https://github.com/thoughtbot/refills/projects) with a focus on accessibility and removal of grid and visual opinion for components. You can see a preview of the work here: http://refills.netlify.com/

Existing components and patterns from the 0.2.0 release will be provided as-is (no longer maintained) until the new version is released.
