### ISSUE TITLE
Expander sometimes sticks on page load

### ISSUE THREAD

**Issue by jbernsie** [thoughtbot/refills#419]
building a rails app and have used the generator to import the expander component into my app, and it works fine, however every I've noticed every 2 or 3 page loads, the expander does not trigger reload the page, and it works fine again. The fact its not a persistent problem tells me its setup fine and working however would like to know if anyone else has experienced this behaviour.

**Comment by tysongach** [comment]
I’m closing this as we are focusing our efforts on a [new, rewritten Refills library](https://github.com/thoughtbot/refills/projects) with a focus on accessibility and removal of grid and visual opinion for components. You can see a preview of the work here: http://refills.netlify.com/

Existing components and patterns from the 0.2.0 release will be provided as-is (no longer maintained) until the new version is released.
