### ISSUE TITLE
Flex-boxes issue on 5k Monitor on Safari / iMac

### ISSUE THREAD

**Issue by iandstanley** [thoughtbot/refills#422]
Odd one here ... 

- works perfectly OK on Chrome on any platform including on the iMac
- works perfectly OK when on Safari when you unmaxmise the browser and narrow the browser window to sub 960 px

- flex wraps to THREE across on a larger window within Safari and content overflows 

**Any ideas?** 

> Images from Mac below ... 

> GitHub repository ... see [this commit](https://github.com/doggydips/doggydips.co.uk/tree/42114d92875a6fac6b2612394f171a62a46dc047) 

> and [staging server to show code](https://doggydips-staging.firebaseapp.com/team/) 

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/6939289/23098067/9a3a879c-f63c-11e6-9744-d14bf7658c39.png)
![pastedgraphic-2](https://cloud.githubusercontent.com/assets/6939289/23098066/9a3908f4-f63c-11e6-8398-9a443e5fb1a0.png)

**Comment by tysongach** [comment]
@iandstanley Are you globally setting `img` elements to have a `max-width: 100%;`?
