### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by moshemo** [thoughtbot/refills#423]
It seems to me that there are some conflicts between bitters, neat and refills.  I have gotten errors about undefined variables and mixins.  From searching around, my understanding is that bitters requires version 5.0 beta of Bourbon whereas refills does not work with version 5.0.

As such, I am wondering how to get started with all four elements.  That is to say, which versions should I download so that I can have a working system until such time as refills is updated?

On that note -- is there any estimation as to when refills will be updated?

Thanks and be well.

**Comment by nicholasshirley** [comment]
After spending a couple of days fighting with this, the only way I was able to get the refills to work was to downgrade to the following versions:

bourbon v. 4.3.2
bitters v. 1.2.0
neat v 1.7.3

**Comment by BrandonElder** [comment]
I've been having the same problems getting refills to work.  Tons of undefined variables/mixins errors which has been a headache.  I'm going to try downgrading versions as well.

**Comment by li-xinyang** [comment]
I am experiencing the similar issue, missing variables/mixins.

**Comment by tysongach** [comment]
Refills is not yet compatible with Neat 2.0. It is, however, up to date with Bourbon 5.0. The dependencies can be found in the readme: https://github.com/thoughtbot/refills#requirements

**Comment by weareREASON** [comment]
Any news on when this will be compatible the neat 2.0

**Comment by tysongach** [comment]
We are actively working on the next version of Refills, which will de-couple it from Neat all-together. Refills, as it is today, will not be updated to work with Neat 2.0.

The current Refills requirements are:

- Sass 3.3+
- Bourbon 5.0+
- Neat < 2.0, >= 1.6
