### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by psychonaut04** [thoughtbot/refills#426]
I'm new to ruby, i'm installed Sass 3.4.23, Bourbon(last version) and Neat 1.8.0. I installed Bourbon and Neat on css folder, converted my css to .scss and imported it on my page, and imported Bourbon and Neat on the .scss file.

Refills components still doesn't work, i'm missing something?

**Comment by tysongach** [comment]
@psychonaut04 What is the error you are receiving?

**Comment by psychonaut04** [comment]
I don't receive any errors, the components just don't appear, i'm new to ruby so i don't know if i did the entire thing. I've searched on so many tutorials as well.
I have a css folder with bourbon and neat and a .scss with the component style(i tried with .css too).

**Comment by tysongach** [comment]
@psychonaut04 Is the code open-source where I can see it?

Refills is a collection of HTML, CSS and JavaScript components, no Ruby needed. Did you follow the [installation instructions](https://github.com/thoughtbot/refills#installation), copy-pasting the components into your project?

**Comment by psychonaut04** [comment]
I installed Bourbon, Neat and Sass via RubyGems, like in Installation sections

**Comment by tysongach** [comment]
@psychonaut04 And how are you compiling your Sass; what is your dev environment? Is the code open-source where I can see it?

**Comment by psychonaut04** [comment]
@tysongach I just started the development, so i'm only starting the layout, i'll put them on github. Maybe you will laugh with a beginner mistake.

**Comment by tysongach** [comment]
@psychonaut04 How are you compiling your Sass into CSS?

**Comment by psychonaut04** [comment]
@tysongach ? I used Sass to convert css to scss

**Comment by tysongach** [comment]
@psychonaut04 From the command line? I see three Sass files in `public_html/css/`, so just trying to understand what is being compiled an where.

Also, which Refills component are you trying to use?

**Comment by psychonaut04** [comment]
@tysongach Yes, from command line, i'm trying to use the Tooltip component. Oh, i forgot to delete, sorry, i'm only using css/maincss.scss

**Comment by tysongach** [comment]
@psychonaut04 Thanks for all the info! I found a few issues:

1. Your `index.html` file [is importing a stylesheet](https://github.com/psychonaut04/psychounaut04-AAC/blob/master/public_html/index.html#L11) called `maincss.scss`. That file should be a `.css` file (not `.scss`).
1. `maincss.css` also does _not_ have the `tooltip` styles inside it.
1. Your CSS `link` in `index.html` is missing the ending `>` at the end of the line.

I [opened a PR](https://github.com/psychonaut04/psychounaut04-AAC/pull/1) on your repo with fixes for the above and I removed all of the Sass/CSS except `maincss.scss` and its output CSS.

Finally, when I tried to compile `maincss.scss` it did throw an error: `error maincss.scss (Line 280: Invalid CSS after "}": expected "}", was "")`. It looks like an ending `}` was missing somewhere.

**Comment by psychonaut04** [comment]
@tysongach Oh thank you so much. The Tooltip is working now! You put the } ? I can find where is missing if not,

**Comment by tysongach** [comment]
> You put the } ? I can find where is missing if not,

Yes, I just threw one at the very end. Not sure exactly where it is missing.

**Comment by psychonaut04** [comment]
@tysongach Ok, thanks! You helped me alot. I didn't saw these issues, i was thinking that something was wrong with the installation.
