### ISSUE TITLE
Refills No Longer Work

### ISSUE THREAD

**Issue by bgarrant** [thoughtbot/refills#434]
I am using PrePros which has the latest stable releases of Bourbon 4.3.3 and Neat 2.0.  I try to use Refills and they fail with Neat 2.0.  Is there any way to get a couple of them to work?  How to I roll bank Neat to a version that works?

**Comment by tysongach** [comment]
Hi @bgarrant!

Refills is not currently compatible with Neat 2.0. We are actively working on the next version of Refills, which will actually de-couple it from Neat all-together, but it is a WIP.

I‘ve not used PrePros before, have you have reached out to their support on how to lock Neat to a previous version?

**Comment by bgarrant** [comment]
I will ask them thanks.  Loving the new Neat.  I am still using Bourbon 4.3.3 but will have to try 5.  Are you planning on a navigation refill?  That is the one I was after.  Anything in the works on that one by chance?

**Comment by tysongach** [comment]
The next version of Refills will have a focus on smaller, more maintainable components that are accessible out-of-the-box. You can follow along here: https://github.com/thoughtbot/refills/projects

**Comment by bgarrant** [comment]
Are the old Refills pretty dated or can we still use them? Just curious if worth rolling back Neat to v1.8.

**Comment by tysongach** [comment]
The current/old Refills are very dated, yes. Personally and honestly, I would not encourage using them.

**Comment by bgarrant** [comment]
Thanks for advice. Can't wait to everything to come out of beta. You guys make great stuff.

**Comment by tysongach** [comment]
Thanks! We’re excited, too.
