### ISSUE TITLE
Older version of refills

### ISSUE THREAD

**Issue by weareREASON** [thoughtbot/refills#436]
Can we still access older versions of refills with all the example code?

**Comment by tysongach** [comment]
Historically, Refills has not been properly versioned, but it also hasn’t seen a lot of iterations. Can you explain what you need an older version for? What specific components are you after?

The [Refills website](http://refills.bourbon.io/) reflects the current snippets, but is not versioned, so any changes to the snippets cannot be viewed there. But everything is tracked here in GitHub, so you can always [cruise through the commit history](https://github.com/thoughtbot/refills/commits/master).
