### ISSUE TITLE
npm installed Refills but I cant import it...

### ISSUE THREAD

**Issue by heswebs** [thoughtbot/refills#440]
I am new to bourbon and gulp, I have installed bourbon and neat they seem to work. However, I am also trying to create a nav with refills. I did npm install the refill packages but I have no idea how to use it. I tried to import the scss like what I did to bourbon and neat but it does not work ... I am wondering if I am doing it wrong?  is there anything that I need to set up in gulpfile.js?   I can't even use the media queries.

**Comment by tysongach** [comment]
Refills is not a library of code tools like Bourbon and Neat are and therefore is also not an npm package.

You can use Refills by going to the [website](http://refills.bourbon.io/) and copy-pasting code into your project: https://github.com/thoughtbot/refills#installation

**Comment by heswebs** [comment]
Thank you for the fast reply. I currently have the following installed:
"bourbon": "^4.3.4",
"bourbon-neat": "^2.0.0"
I want to use the responsive navigation on the website.  do my bourbon and neat version compatible with that?

**Comment by tysongach** [comment]
You can always see what Refills requires in the README: https://github.com/thoughtbot/refills#requirements

Currently, Refills needs Neat 1.x and is not compatible with 2.0, so you’ll need to downgrade Neat.

**Comment by heswebs** [comment]
Thank you, I will try it right away. it is a surprise project that I have to use gulp build with bourbon so I barely started yesterday. using both really opened my eyes.

**Comment by heswebs** [comment]
Thank you, It is working now!
