### ISSUE TITLE
Undefined mixin 'media'

### ISSUE THREAD

**Issue by adityaanandmc** [thoughtbot/refills#441]
Installed `bourbon` and `bitter` via `gem`.
Got the `Undefined mixin media` error when I ported over the [table](http://refills.bourbon.io/#er-toc-id-17) snippet from refills!
 
Googling lead me to the [issue](https://github.com/thoughtbot/bourbon/issues/874)!
I'm guessing `media` also falls into that category!
Is there any update on when the next version of `refills` will be out?

**Comment by tysongach** [comment]
The `media` mixin is part of Neat (the 1.x release cycle, specifically), which Refills is dependent on. Installing Neat 1.8 should fix your issue.

The next release of Refills will be majorly different and no longer dependent on Neat. There is no release date at this time.
