### ISSUE TITLE
Refills components aren't working/Needs Update

### ISSUE THREAD

**Issue by adrianwarholm** [thoughtbot/refills#445]
## Github Link:
https://github.com/adrianwarholm/Sass-Tut

## Editor Information
- Using Atom
- Compiling with sass command line(sass cli)
- All folders were imported from git and pasted into my project

## Dilemma

I have neat,bourbon,and bitters installed into my project. However, the Refills components will not work when I copy/paste the HTML and CSS code. Thus, I cannot see the styling refills shows. Refills shouldn't pose this issue as it is based off of bourbon, neat, and bitters. I also installed their recent versions from thoughtbot.

Examples given on the refills page aren't updated. Only the projects are but not the examples in refills.bourbon.io

All help is appreciated to solve this.

## My Thoughts
I believe Neat 2.0, the most recent Neat version, is not compatible with Refills. Refills requires a thorough update to be compatible. If someone could add a version of refills that is, it would be great. 

**So why do you need refills if you have the libraries and refills is only code based off of them?**

_Refills helps to understand the code. I prefer the BBNR/Bourbon over Bootstrap because of how easily I can infuse my wireframed ideas into them and how lightweight they are. It's also super beautiful and matches my art style._

## Short-Note
_I am a teenage developer and relatively entry-level. I'm learning about sass frameworks and libraries. Thus, I am relatively new to bourbon/bitters/neat/refills. I have been looking for solutions for five days straight prior to this._

**Comment by creuter** [comment]
Hello! As noted in the README, Refills is not currently compatible with Neat 2.0. We are actively working on the next version of Refills, which will actually de-couple it from Neat all-together, but it is a WIP. You can get a sneak peek here: http://refills.netlify.com

**Comment by creuter** [comment]
If you remove any `@include media(...)` or any `@include span-column(...)` mixins, you should get most of the way there.
