### ISSUE TITLE
"Copy CSS" and "Copy HTML" buttons don't work

### ISSUE THREAD

**Issue by DavidRagone** [thoughtbot/refills#448]
On hover over any of the copy buttons[1] on http://refills.bourbon.io/ I get the following:

```javascript
Uncaught TypeError: Cannot read property 'style' of undefined
    at p.reposition (all.js:1436)
    at p.setCurrent (all.js:1436)
    at HTMLAnchorElement.d (all.js:1436)
```

I've yet to look into where this code is generated to troubleshoot further.

[1] e.g. these
![image](https://user-images.githubusercontent.com/1452099/36804956-f6ed0658-1c70-11e8-9e0f-e836027f89fa.png)

**Comment by tysongach** [comment]
We've decided to deprecate this project, as we've not found the time to keep it maintained and updated.
